"""
Birhan AI
Shared Board Rendering Engine

============================================================
WHY THIS FILE EXISTS
============================================================

services/video_generator.py (every video frame) and
services/visual_generator.py (the static per-scene gallery PNG
shown in lesson.html) both import from here and call the exact
same functions, so the gallery image and the video frame for a
given scene are generated by identical code.

============================================================
CHANGES IN THIS VERSION
============================================================

1. IMAGE GENERATION COMPLETELY REMOVED. The diagram panel (both
   the Pexels reference-photo lookup and the generated fallback
   icon) was producing inaccurate/unrelated images, so all of it
   - fetch_reference_image(), render_diagram_icon(),
   draw_diagram_panel(), the VISUAL_TYPE_IMAGE_QUERIES table, and
   every call site - has been removed. Every scene now renders as
   a pure text board: title + bullets only. Removing the diagram
   panel also frees up the board's horizontal writing width
   (BOARD_TEXT_MAX_WIDTH no longer reserves space for it), so
   text now has the full board width to work with.

2. TEXT BOUNDARY / CLIPPING FIX. All text (title + bullets) is
   now guaranteed to stay fully inside the visible board and
   video frame:
   - The title is measured and, if it would ever be wider than
     the safe horizontal area, its font is shrunk until it fits
     before being centered - it can never run past the left/right
     edges.
   - Bullet wrapping already respected BOARD_TEXT_MAX_WIDTH, but
     drawing is now also hard-clipped vertically: a bullet line is
     only drawn if it fits completely above BOARD_TEXT_BOTTOM_Y
     (the same boundary assign_visual_style() already plans
     against), so no line can ever bleed below the writable board
     area even in an edge-case rounding situation. A safe left/
     right margin is enforced on every line too.
   - assign_visual_style()'s board-splitting math is unchanged in
     behavior other than using the new, wider BOARD_TEXT_MAX_WIDTH.

============================================================
BOARD-WRITING MODEL (persistent, cross-scene board)
============================================================

assign_visual_style() walks the COMPLETE, final scene list once
and simulates a real notebook/whiteboard:

- A single fixed font size is used for the whole board (a real
  board doesn't resize its own handwriting scene to scene).
- Each scene's bullet points are measured against how much
  vertical room is left on the CURRENT board. If they fit, they
  are appended below whatever is already written; if they don't
  fit (and the board already has something on it), a brand new
  board is started - fresh theme, fresh camera angle, writing
  from the top again.
- Every scene remembers ("board_prior_bullets") the full text of
  everything earlier scenes already wrote on its board, so the
  video frame for ANY scene can redraw the whole board exactly as
  a viewer would have last seen it, then continue writing that
  scene's own new lines in sync with its narration. Nothing is
  ever erased just because a scene boundary passed.
- In the rare case a single scene's own notes are too long to
  fit even on a completely empty board, that one scene's font is
  shrunk just enough to fit (a real teacher writing smaller
  rather than starting a needless third board mid-thought).

============================================================
CAMERA (9 simulated framings, real visible motion)
============================================================

This is a static 2D PIL board, not a literal 3D camera, so each
preset crops-and-zooms the rendered CONTENT region (never the
footer/progress bar) to simulate a different framing. A new
board always gets a new camera angle, chosen from a fixed cycle
order picked specifically so consecutive angles differ sharply
in zoom and framing (never two similar-looking angles back to
back). Whenever a board's angle differs from the previous
board's, the first scene on the new board eases smoothly from
the old framing into the new one over the opening ~1.4s of the
clip, so the change is an actual, visible camera move.
"""

import os
import re
from functools import lru_cache

from PIL import Image, ImageDraw, ImageFont

from config import VIDEO_WIDTH, VIDEO_HEIGHT

# Pillow's LANCZOS resample constant moved to Image.Resampling in newer
# versions; some Pylance/Pillow stub combinations don't resolve
# Image.LANCZOS directly even though it still works at runtime. Resolve
# it once, defensively, so both old and new Pillow/stub versions are
# satisfied. (Still used by apply_camera_transform's resize below.)
try:
    RESAMPLE_LANCZOS = Image.Resampling.LANCZOS
except AttributeError:
    RESAMPLE_LANCZOS = Image.LANCZOS

# ============================================================
# LAYOUT CONSTANTS
# ============================================================

# The board's "teaching content" area (title + bullets). The
# camera transform is applied ONLY to this region, never to the
# footer or progress bar below it, so a camera zoom/pan can never
# clip the scene counter or crop the progress indicator off-screen.
CONTENT_HEIGHT = 660

WHITE = (255, 255, 255)
GRAY = (130, 130, 130)

# Fixed board-writing area. A single font size is used across an
# entire board (see BOARD-WRITING MODEL above) so handwriting
# doesn't visually change size scene to scene on the same board.
# These bounds are the hard boundary: nothing is ever drawn
# outside BOARD_TEXT_TOP_Y..BOARD_TEXT_BOTTOM_Y vertically, or
# past the safe left/right margins horizontally.
BOARD_TEXT_TOP_Y = 140
BOARD_TEXT_BOTTOM_Y = 625
BOARD_TEXT_MAX_HEIGHT = BOARD_TEXT_BOTTOM_Y - BOARD_TEXT_TOP_Y

BOARD_TEXT_FONT_SIZE = 34
BOARD_TEXT_MIN_FONT_SIZE = 16

BOARD_TEXT_LEFT_X = 90
BOARD_TEXT_RIGHT_MARGIN = 90

# No diagram panel anymore, so the writable width now spans the
# full safe board area instead of reserving space on the right.
BOARD_TEXT_MAX_WIDTH = VIDEO_WIDTH - BOARD_TEXT_LEFT_X - BOARD_TEXT_RIGHT_MARGIN

# Safe margins for the title as well, so a very long title can
# never be measured/centered past the video's left/right edges.
TITLE_SAFE_MARGIN = 60
TITLE_MAX_WIDTH = VIDEO_WIDTH - (2 * TITLE_SAFE_MARGIN)
TITLE_MAX_FONT_SIZE = 40
TITLE_MIN_FONT_SIZE = 20


# ============================================================
# FONT PATHS (Amharic + Latin)
# ============================================================

def get_font_path(bold=False):

    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    project_fonts = [
        os.path.join(project_root, "fonts", "NotoSansEthiopic-Bold.ttf" if bold else "NotoSansEthiopic-Regular.ttf"),
    ]

    if bold:
        candidates = project_fonts + [
            "C:/Windows/Fonts/NotoSansEthiopic-Bold.ttf",
            "C:/Windows/Fonts/NotoSansEthiopic-Regular.ttf",
            "C:/Windows/Fonts/NotoSansEthiopic.ttf",
            "C:/Windows/Fonts/arialbd.ttf",
            "C:/Windows/Fonts/Arialbd.ttf",
            "C:/Windows/Fonts/calibrib.ttf",
            "C:/Windows/Fonts/segoeuib.ttf",
            "/usr/share/fonts/truetype/noto/NotoSansEthiopic-Bold.ttf",
            "/usr/share/fonts/truetype/noto/NotoSansEthiopic-Regular.ttf",
            "/usr/share/fonts/truetype/noto/NotoSansEthiopic.ttf",
            "/usr/share/fonts/truetype/noto-ethiopic/NotoSansEthiopic-Bold.ttf",
            "/usr/share/fonts/opentype/noto/NotoSansEthiopic-Bold.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
            "/usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf",
        ]
    else:
        candidates = project_fonts + [
            "C:/Windows/Fonts/NotoSansEthiopic-Regular.ttf",
            "C:/Windows/Fonts/NotoSansEthiopic.ttf",
            "C:/Windows/Fonts/NotoSansEthiopic-Bold.ttf",
            "C:/Windows/Fonts/arial.ttf",
            "C:/Windows/Fonts/Arial.ttf",
            "C:/Windows/Fonts/calibri.ttf",
            "C:/Windows/Fonts/segoeui.ttf",
            "/usr/share/fonts/truetype/noto/NotoSansEthiopic-Regular.ttf",
            "/usr/share/fonts/truetype/noto/NotoSansEthiopic.ttf",
            "/usr/share/fonts/truetype/noto-ethiopic/NotoSansEthiopic-Regular.ttf",
            "/usr/share/fonts/opentype/noto/NotoSansEthiopic-Regular.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
            "/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf",
        ]

    for font_path in candidates:
        if os.path.exists(font_path):
            return font_path

    return None


@lru_cache(maxsize=None)
def load_font(size, bold=False):

    font_path = get_font_path(bold=bold)

    if font_path:
        try:
            return ImageFont.truetype(font_path, size)
        except Exception:
            pass

    return ImageFont.load_default()


# ============================================================
# BOARD THEMES (10 designs, each with its own marker shape)
# ============================================================

PALETTES = {

    # Used on light backgrounds - deep, saturated category colors.
    "deep": {
        "formula": (200, 60, 50),
        "definition": (35, 140, 90),
        "heading": (25, 45, 80),
        "example": (215, 130, 30),
        "key_term": (150, 60, 170),
        "note": (0, 130, 140),
    },

    # Used on dark backgrounds - bright colors for contrast.
    "bright": {
        "formula": (255, 120, 110),
        "definition": (130, 235, 175),
        "heading": (255, 255, 255),
        "example": (255, 195, 120),
        "key_term": (220, 160, 255),
        "note": (130, 225, 235),
    },
}

BOARD_THEMES = [
    {"key": "classic_white", "background": (255, 255, 255), "border": (210, 215, 225),
     "divider": (45, 100, 180), "palette": "deep", "marker": "circle"},

    {"key": "green_chalk", "background": (20, 70, 45), "border": (150, 190, 160),
     "divider": (210, 230, 210), "palette": "bright", "marker": "dash"},

    {"key": "navy_slate", "background": (18, 28, 48), "border": (120, 150, 200),
     "divider": (150, 180, 230), "palette": "bright", "marker": "diamond"},

    {"key": "black_board", "background": (25, 25, 25), "border": (95, 95, 95),
     "divider": (230, 230, 230), "palette": "bright", "marker": "star"},

    {"key": "warm_sand", "background": (250, 244, 230), "border": (205, 185, 145),
     "divider": (180, 140, 80), "palette": "deep", "marker": "square"},

    {"key": "sky_whiteboard", "background": (245, 250, 255), "border": (150, 190, 230),
     "divider": (45, 110, 190), "palette": "deep", "marker": "ring"},

    {"key": "forest_green", "background": (236, 246, 236), "border": (125, 175, 125),
     "divider": (45, 120, 60), "palette": "deep", "marker": "triangle"},

    {"key": "deep_purple", "background": (32, 22, 48), "border": (150, 110, 200),
     "divider": (200, 170, 240), "palette": "bright", "marker": "cross"},

    {"key": "charcoal_modern", "background": (36, 39, 43), "border": (115, 120, 125),
     "divider": (180, 200, 220), "palette": "bright", "marker": "arrow"},

    {"key": "ocean_teal", "background": (231, 249, 248), "border": (120, 190, 190),
     "divider": (10, 120, 120), "palette": "deep", "marker": "square_ring"},
]

BOARD_THEME_BY_KEY = {theme["key"]: theme for theme in BOARD_THEMES}

DEFAULT_THEME = BOARD_THEMES[0]


def theme_for_scene(scene):

    key = scene.get("board_theme") if isinstance(scene, dict) else None

    return BOARD_THEME_BY_KEY.get(key, DEFAULT_THEME)


# ============================================================
# CAMERA ANGLES (9 simulated framings)
#
# HONESTY NOTE: this is a static 2D PIL board, not a real 3D
# scene, so there is no literal camera to move. Each preset
# instead crops-and-zooms the rendered CONTENT region (never
# the footer/progress bar) to simulate a different framing.
#
# Zoom levels are spread deliberately wide (1.00 up to 1.28) and
# CAMERA_CYCLE_ORDER (below) is hand-picked so that two boards in
# a row never land on similar-looking angles - every board change
# is a genuinely different, easily-noticed framing.
# ============================================================

CAMERA_ANGLES = [
    {"key": "wide", "zoom": 1.00, "offset_x": 0.50, "offset_y": 0.45},
    {"key": "center_focus", "zoom": 1.10, "offset_x": 0.50, "offset_y": 0.35},
    {"key": "left_lean", "zoom": 1.16, "offset_x": 0.12, "offset_y": 0.35},
    {"key": "right_lean", "zoom": 1.16, "offset_x": 0.85, "offset_y": 0.35},
    {"key": "top_emphasis", "zoom": 1.14, "offset_x": 0.40, "offset_y": 0.05},
    {"key": "close_up", "zoom": 1.28, "offset_x": 0.45, "offset_y": 0.35},
    {"key": "lower_third", "zoom": 1.14, "offset_x": 0.40, "offset_y": 0.65},
    {"key": "diagonal_left", "zoom": 1.20, "offset_x": 0.20, "offset_y": 0.20},
    {"key": "diagonal_right", "zoom": 1.20, "offset_x": 0.78, "offset_y": 0.25},
]

CAMERA_BY_KEY = {camera["key"]: camera for camera in CAMERA_ANGLES}

DEFAULT_CAMERA = CAMERA_ANGLES[0]

# The order boards cycle through cameras in. Deliberately ordered
# so adjacent entries have very different zoom/offset, guaranteeing
# a real, visible jump every time a new board starts.
CAMERA_CYCLE_ORDER = [
    "wide", "close_up", "diagonal_left", "top_emphasis", "right_lean",
    "lower_third", "left_lean", "diagonal_right", "center_focus",
]

# How long (in seconds) the simulated camera takes to ease from the
# previous board's framing into a new board's framing, at the start
# of the first scene of the new board. Clamped per-scene against
# that scene's own duration so a very short scene can never spend
# its whole runtime mid-transition.
CAMERA_TRANSITION_SECONDS = 1.4


def camera_for_scene(scene):

    key = scene.get("camera_angle") if isinstance(scene, dict) else None

    return CAMERA_BY_KEY.get(key, DEFAULT_CAMERA)


def _ease_in_out(progress):

    progress = max(0.0, min(1.0, progress))

    if progress < 0.5:
        return 4 * (progress ** 3)

    p = -2 * progress + 2

    return 1 - (p ** 3) / 2


def apply_camera_transform(image, camera, transition_from=None, time_position=0.0, duration=1.0):

    """
    Crops-and-zooms the CONTENT region to simulate `camera`'s
    framing. When `transition_from` (another camera dict) is
    given, the zoom/offset are eased from that camera's framing
    into `camera`'s framing over the first CAMERA_TRANSITION_SECONDS
    (clamped to this scene's own duration) of the clip, so the
    angle change is an actual, visible camera move instead of an
    instant, invisible swap.
    """

    target_zoom = camera.get("zoom", 1.0)
    target_offset_x = camera.get("offset_x", 0.5)
    target_offset_y = camera.get("offset_y", 0.5)

    if transition_from is not None:

        effective_transition_seconds = CAMERA_TRANSITION_SECONDS

        if duration and duration > 0:
            effective_transition_seconds = min(
                CAMERA_TRANSITION_SECONDS,
                max(0.3, duration * 0.6),
            )

        raw_progress = (
            time_position / effective_transition_seconds
            if effective_transition_seconds > 0
            else 1.0
        )

        progress = _ease_in_out(raw_progress)

        from_zoom = transition_from.get("zoom", 1.0)
        from_offset_x = transition_from.get("offset_x", 0.5)
        from_offset_y = transition_from.get("offset_y", 0.5)

        zoom = from_zoom + (target_zoom - from_zoom) * progress
        offset_x = from_offset_x + (target_offset_x - from_offset_x) * progress
        offset_y = from_offset_y + (target_offset_y - from_offset_y) * progress

    else:

        zoom = target_zoom
        offset_x = target_offset_x
        offset_y = target_offset_y

    if zoom <= 1.001:
        return image

    width, height = image.size

    crop_width = max(1, int(width / zoom))
    crop_height = max(1, int(height / zoom))

    max_x = max(0, width - crop_width)
    max_y = max(0, height - crop_height)

    left = int(max_x * offset_x)
    top = int(max_y * offset_y)

    cropped = image.crop((left, top, left + crop_width, top + crop_height))

    return cropped.resize((width, height), RESAMPLE_LANCZOS)


# ============================================================
# TEXT HELPERS
# ============================================================

def clean_text(text):

    if text is None:
        return ""

    text = str(text)
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"([.!?]){2,}", r"\1", text)

    lines = []

    for line in text.split("\n"):
        line = re.sub(r"[ \t]+", " ", line).strip()
        if line:
            lines.append(_ensure_terminal_punctuation(line))

    return "\n".join(lines)


def _ensure_terminal_punctuation(line):

    stripped = line.strip()

    if not stripped:
        return stripped

    if stripped[-1] in ".!?:)\u201d\"'":
        return stripped

    if len(stripped.split()) <= 3:
        return stripped

    return stripped + "."


def get_text_width(draw, text, font):

    if not text:
        return 0

    bbox = draw.textbbox((0, 0), text, font=font)

    return bbox[2] - bbox[0]


def wrap_text(draw, text, font, max_width):

    text = text.strip()

    if not text:
        return []

    words = text.split()

    lines = []
    current_line = ""

    for word in words:

        test_line = (current_line + " " + word).strip()

        if get_text_width(draw, test_line, font) <= max_width:
            current_line = test_line
        else:
            if current_line:
                lines.append(current_line)
            current_line = word

    if current_line:
        lines.append(current_line)

    return lines


def get_scene_text(scene):

    if not isinstance(scene, dict):
        return ""

    text = (
        scene.get("board_text", "")
        or scene.get("narration", "")
        or scene.get("text", "")
        or scene.get("explanation", "")
        or scene.get("content", "")
        or scene.get("description", "")
        or scene.get("title", "")
    )

    return clean_text(text)


def get_scene_title(scene):

    if not isinstance(scene, dict):
        return ""

    return clean_text(scene.get("title", ""))


# ============================================================
# BULLET SPLITTING / COLORING / MARKERS
# ============================================================

def split_into_bullet_points(text):

    text = clean_text(text)

    if not text:
        return []

    bullet_points = []
    seen_normalized = set()

    for raw_line in text.split("\n"):

        line = raw_line.strip()

        if not line:
            continue

        line = re.sub(r"^[•●▪◦▸★❖►✧◆*\-–—]\s*", "", line).strip()

        if not line:
            continue

        numbered_parts = re.split(
            r"(?<=[.!?])\s+(?=(?:\d+[\.)]|[A-Z][\.)]))", line
        )

        parts_to_process = numbered_parts if len(numbered_parts) > 1 else re.split(
            r"(?<=[.!?])\s+", line
        )

        for part in parts_to_process:

            part = part.strip()

            if not part:
                continue

            normalized = re.sub(r"\s+", " ", part.lower())

            if normalized in seen_normalized:
                continue

            seen_normalized.add(normalized)
            bullet_points.append(part)

    return bullet_points


def pick_bullet_color(theme, text):

    palette = PALETTES.get(theme.get("palette", "deep"), PALETTES["deep"])

    lowered = text.lower()

    looks_like_formula = bool(re.search(r"[=+\-*/^]", text)) and any(
        character.isdigit() for character in text
    )

    looks_like_definition = (
        ":" in text or " si unit" in lowered or lowered.startswith("definition")
    )

    looks_like_example = (
        lowered.startswith("example")
        or lowered.startswith("e.g.")
        or " e.g." in lowered
        or lowered.startswith("for example")
    )

    looks_like_key_term = (
        len(text.split()) <= 3 and not looks_like_formula and not looks_like_definition
    )

    if looks_like_formula:
        return palette["formula"]

    if looks_like_definition:
        return palette["definition"]

    if looks_like_example:
        return palette["example"]

    if looks_like_key_term:
        return palette["key_term"]

    return palette["note"]


def draw_marker(draw, x, y, size, color, shape):

    if shape == "circle":
        draw.ellipse([x, y, x + size, y + size], fill=color)

    elif shape == "square":
        draw.rectangle([x, y, x + size, y + size], fill=color)

    elif shape == "square_ring":
        draw.rectangle([x, y, x + size, y + size], outline=color, width=3)

    elif shape == "diamond":
        mid = size / 2
        draw.polygon(
            [(x + mid, y), (x + size, y + mid), (x + mid, y + size), (x, y + mid)],
            fill=color,
        )

    elif shape == "star":
        cx, cy, r = x + size / 2, y + size / 2, size / 2
        points = []
        for i in range(5):
            angle = -1.5707963 + i * (2 * 3.14159265 / 5)
            points.append((cx + r * _cos(angle), cy + r * _sin(angle)))
            angle_inner = angle + (3.14159265 / 5)
            points.append((cx + (r / 2.3) * _cos(angle_inner), cy + (r / 2.3) * _sin(angle_inner)))
        draw.polygon(points, fill=color)

    elif shape == "triangle":
        draw.polygon(
            [(x + size / 2, y), (x + size, y + size), (x, y + size)],
            fill=color,
        )

    elif shape == "ring":
        draw.ellipse([x, y, x + size, y + size], outline=color, width=3)

    elif shape == "cross":
        third = size / 3
        draw.rectangle([x + third, y, x + 2 * third, y + size], fill=color)
        draw.rectangle([x, y + third, x + size, y + 2 * third], fill=color)

    elif shape == "arrow":
        mid = size / 2
        draw.polygon(
            [(x, y + mid - 3), (x + size * 0.6, y + mid - 3), (x + size * 0.6, y),
             (x + size, y + mid), (x + size * 0.6, y + size), (x + size * 0.6, y + mid + 3),
             (x, y + mid + 3)],
            fill=color,
        )

    else:  # "dash"
        draw.rectangle([x, y + size * 0.35, x + size, y + size * 0.65], fill=color)


def _cos(angle):
    import math
    return math.cos(angle)


def _sin(angle):
    import math
    return math.sin(angle)


# ============================================================
# WORD-LEVEL VOICE <-> BOARD ALIGNMENT
# ============================================================

def _normalize_word(word):

    return re.sub(r"[^\w']+", "", str(word or "")).lower()


def _tokenize_words(text):

    if not text:
        return []

    return [word for word in re.split(r"\s+", text.strip()) if word]


def align_words_to_speech(board_words, speech_boundaries, lookahead=20):

    normalized_speech = [_normalize_word(b.get("text", "")) for b in speech_boundaries]

    total_speech_words = len(speech_boundaries)

    pointer = 0

    aligned = []

    for word in board_words:

        target = _normalize_word(word)

        found_index = None

        if target:

            window_end = min(total_speech_words, pointer + lookahead)

            for index in range(pointer, window_end):
                if normalized_speech[index] == target:
                    found_index = index
                    break

            if found_index is None:
                for index in range(pointer, total_speech_words):
                    if normalized_speech[index] == target:
                        found_index = index
                        break

        if found_index is not None:

            boundary = speech_boundaries[found_index]

            aligned.append({"start": boundary["start"], "end": boundary["end"], "matched": True})

            pointer = found_index + 1

        else:

            aligned.append({"start": None, "end": None, "matched": False})

    return aligned


def _fill_unmatched_word_times(aligned, duration):

    total_words = len(aligned)

    if total_words == 0:
        return aligned

    matched_indices = [i for i, e in enumerate(aligned) if e["matched"]]

    if not matched_indices:

        for index in range(total_words):
            time_value = duration * (index + 1) / (total_words + 1)
            aligned[index]["start"] = time_value
            aligned[index]["end"] = time_value

        return aligned

    first_matched = matched_indices[0]
    first_start = aligned[first_matched]["start"]

    if first_matched > 0:
        for index in range(first_matched):
            fraction = (index + 1) / (first_matched + 1)
            time_value = first_start * fraction
            aligned[index]["start"] = time_value
            aligned[index]["end"] = time_value

    for position in range(len(matched_indices) - 1):

        left_index = matched_indices[position]
        right_index = matched_indices[position + 1]

        gap_size = right_index - left_index - 1

        if gap_size <= 0:
            continue

        left_end = aligned[left_index]["end"]
        right_start = aligned[right_index]["start"]
        gap_duration = max(right_start - left_end, 0.0)

        for offset in range(1, gap_size + 1):
            time_value = left_end + (gap_duration * offset / (gap_size + 1))
            aligned[left_index + offset]["start"] = time_value
            aligned[left_index + offset]["end"] = time_value

    last_matched = matched_indices[-1]
    last_end = aligned[last_matched]["end"]

    if last_matched < total_words - 1:
        remaining = total_words - 1 - last_matched
        for offset in range(1, remaining + 1):
            time_value = last_end + ((duration - last_end) * offset / (remaining + 1))
            aligned[last_matched + offset]["start"] = time_value
            aligned[last_matched + offset]["end"] = time_value

    return aligned


def build_bullet_word_timelines(bullet_points, duration, word_boundaries=None):

    if duration <= 0:
        duration = 1.0

    board_words = []
    bullet_word_ranges = []

    for bullet_text in bullet_points:

        words = _tokenize_words(bullet_text)
        start_index = len(board_words)
        board_words.extend(words)
        bullet_word_ranges.append((start_index, len(board_words)))

    speech_boundaries = []

    if word_boundaries:

        for boundary in word_boundaries:

            if not isinstance(boundary, dict):
                continue

            try:
                start_time = float(boundary.get("start"))
            except (TypeError, ValueError):
                continue

            try:
                end_time = float(boundary.get("end", start_time))
            except (TypeError, ValueError):
                end_time = start_time

            start_time = max(0.0, min(start_time, duration))
            end_time = max(start_time, min(end_time, duration))

            speech_boundaries.append(
                {"text": boundary.get("text", ""), "start": start_time, "end": end_time}
            )

        speech_boundaries.sort(key=lambda item: item["start"])

    aligned = align_words_to_speech(board_words, speech_boundaries)

    suppressed_indices = set()

    if speech_boundaries:

        for start_index, end_index in bullet_word_ranges:

            bullet_has_match = any(
                aligned[index]["matched"] for index in range(start_index, end_index)
            )

            if not bullet_has_match:
                for index in range(start_index, end_index):
                    suppressed_indices.add(index)

    aligned = _fill_unmatched_word_times(aligned, duration)

    for index in suppressed_indices:
        aligned[index]["start"] = None
        aligned[index]["end"] = None

    timelines = []

    for bullet_text, (start_index, end_index) in zip(bullet_points, bullet_word_ranges):

        words = board_words[start_index:end_index]

        word_starts = [aligned[index]["start"] for index in range(start_index, end_index)]

        timelines.append({"words": words, "word_starts": word_starts})

    return timelines


def get_visible_word_count(word_starts, time_position):

    visible_count = 0

    for start_time in word_starts:
        if start_time is not None and start_time <= time_position:
            visible_count += 1
        else:
            break

    return visible_count


# ============================================================
# PERSISTENT, CROSS-SCENE BOARD ASSIGNMENT
#
# Walks the COMPLETE, final scene list once and simulates a real
# writing board: each scene's bullets are appended below whatever
# is already written on the CURRENT board, using ONE fixed font
# size for the whole board. A new board (fresh theme, fresh
# camera, writing restarts from the top) is only started once the
# current board genuinely has no room left for the next scene's
# notes. Every scene is tagged with "board_prior_bullets" - the
# full text of everything already written on its board by earlier
# scenes - so the frame for any scene can redraw the whole board
# exactly as a viewer would have last seen it before continuing
# to write that scene's own new lines.
# ============================================================

def _bullet_block_height(draw, bullet_text, font, max_width, line_height, gap):

    lines = wrap_text(draw, bullet_text, font, max_width - 55)

    if not lines:
        return 0

    return len(lines) * line_height + gap


def _measure_bullets_height(draw, bullet_points, font, max_width, line_height, gap):

    total = 0.0

    for bullet_text in bullet_points:
        total += _bullet_block_height(draw, bullet_text, font, max_width, line_height, gap)

    return total


def _shrink_font_to_fit(draw, bullet_points, max_width, max_height):

    """
    Fallback for the rare case where a single scene's own notes
    are too long to fit even on a completely empty board at the
    standard board font size. Shrinks the font just for this one
    scene until its notes fit (or, failing that, until the
    minimum readable size is reached).
    """

    for size in range(BOARD_TEXT_FONT_SIZE, BOARD_TEXT_MIN_FONT_SIZE - 1, -2):

        font = load_font(size, bold=False)
        line_height = int(size * 1.45)
        gap = int(size * 0.65)

        total = _measure_bullets_height(draw, bullet_points, font, max_width, line_height, gap)

        if total <= max_height:
            return size, line_height, gap, total

    size = BOARD_TEXT_MIN_FONT_SIZE
    font = load_font(size, bold=False)
    line_height = int(size * 1.45)
    gap = int(size * 0.65)

    total = _measure_bullets_height(draw, bullet_points, font, max_width, line_height, gap)

    return size, line_height, gap, total


def assign_visual_style(scenes):

    """
    Mutates each scene dict in place, setting "board_theme",
    "camera_angle", "board_font_size", "board_prior_bullets", and
    (on the first scene of a new board whose camera differs from
    the previous board's) "camera_transition_from". Call this
    ONCE, on the COMPLETE final scene list (including any
    assessment/closing scenes appended after
    services/lesson_parser.py runs), before generating any scene
    images or video frames.
    """

    if not isinstance(scenes, list):
        return scenes

    probe_image = Image.new("RGB", (VIDEO_WIDTH, CONTENT_HEIGHT))
    ImageDraw.Draw(probe_image).rectangle(
        [0, 0, VIDEO_WIDTH - 1, CONTENT_HEIGHT - 1], fill=WHITE
    )
    probe_draw = ImageDraw.Draw(probe_image)

    default_font = load_font(BOARD_TEXT_FONT_SIZE, bold=False)
    default_line_height = int(BOARD_TEXT_FONT_SIZE * 1.45)
    default_gap = int(BOARD_TEXT_FONT_SIZE * 0.65)

    theme_pointer = 0
    camera_pointer = 0

    used_height = 0.0
    board_prior_bullets = []

    current_theme_key = None
    current_camera_key = None
    previous_camera_key = None

    def start_new_board():

        nonlocal used_height, board_prior_bullets
        nonlocal current_theme_key, current_camera_key, previous_camera_key
        nonlocal theme_pointer, camera_pointer

        previous_camera_key = current_camera_key

        current_theme_key = BOARD_THEMES[theme_pointer % len(BOARD_THEMES)]["key"]
        theme_pointer += 1

        current_camera_key = CAMERA_CYCLE_ORDER[camera_pointer % len(CAMERA_CYCLE_ORDER)]
        camera_pointer += 1

        used_height = 0.0
        board_prior_bullets = []

    for scene in scenes:

        if not isinstance(scene, dict):
            continue

        scene_text = get_scene_text(scene)
        bullet_points = split_into_bullet_points(scene_text) if scene_text else []

        is_new_board_start = False

        if current_theme_key is None:
            start_new_board()
            is_new_board_start = True

        font_size = BOARD_TEXT_FONT_SIZE
        line_height = default_line_height
        gap = default_gap

        required_height = _measure_bullets_height(
            probe_draw, bullet_points, default_font, BOARD_TEXT_MAX_WIDTH, line_height, gap
        )

        if bullet_points and used_height > 0 and used_height + required_height > BOARD_TEXT_MAX_HEIGHT:

            # No room left on the current board for this scene's
            # notes - start a fresh board, writing from the top.
            start_new_board()
            is_new_board_start = True

            required_height = _measure_bullets_height(
                probe_draw, bullet_points, default_font, BOARD_TEXT_MAX_WIDTH, line_height, gap
            )

        if bullet_points and used_height == 0 and required_height > BOARD_TEXT_MAX_HEIGHT:

            # Even a brand new, empty board can't fit this one
            # scene's notes at the standard size - shrink just
            # this scene's font rather than leaving a needless
            # extra board split mid-thought.
            font_size, line_height, gap, required_height = _shrink_font_to_fit(
                probe_draw, bullet_points, BOARD_TEXT_MAX_WIDTH, BOARD_TEXT_MAX_HEIGHT
            )

        scene["board_theme"] = current_theme_key
        scene["camera_angle"] = current_camera_key
        scene["board_font_size"] = font_size
        scene["board_prior_bullets"] = list(board_prior_bullets)

        if (
            is_new_board_start
            and previous_camera_key is not None
            and previous_camera_key != current_camera_key
        ):
            scene["camera_transition_from"] = previous_camera_key
        else:
            scene.pop("camera_transition_from", None)

        board_prior_bullets.extend(bullet_points)
        used_height += required_height

    return scenes


# ============================================================
# LAYOUT / FRAME BUILDING
# ============================================================

def build_scene_render_layout(draw, scene, duration):

    scene_text = get_scene_text(scene)

    if not scene_text:
        return None

    bullet_points = split_into_bullet_points(scene_text)

    if not bullet_points:
        return None

    font_size = (
        scene.get("board_font_size", BOARD_TEXT_FONT_SIZE)
        if isinstance(scene, dict)
        else BOARD_TEXT_FONT_SIZE
    )

    body_font = load_font(font_size, bold=False)
    line_height = int(font_size * 1.45)
    bullet_gap = int(font_size * 0.65)

    max_width = BOARD_TEXT_MAX_WIDTH

    word_boundaries = scene.get("speech_word_boundaries") if isinstance(scene, dict) else None

    word_timelines = build_bullet_word_timelines(
        bullet_points=bullet_points, duration=duration, word_boundaries=word_boundaries,
    )

    return {
        "bullet_points": bullet_points,
        "body_font": body_font,
        "line_height": line_height,
        "bullet_gap": bullet_gap,
        "word_timelines": word_timelines,
        "max_width": max_width,
    }


def _fit_title_font(draw, title, max_width):

    """
    Finds the largest font size (up to TITLE_MAX_FONT_SIZE) at
    which `title` fits within max_width, so a long title can
    never be centered/drawn past the safe left/right edges of the
    board.
    """

    for size in range(TITLE_MAX_FONT_SIZE, TITLE_MIN_FONT_SIZE - 1, -2):

        font = load_font(size, bold=True)

        if get_text_width(draw, title, font) <= max_width:
            return font

    return load_font(TITLE_MIN_FONT_SIZE, bold=True)


def _draw_board_title(draw, scene, theme):

    title = get_scene_title(scene)

    if not title:
        return

    palette = PALETTES.get(theme.get("palette", "deep"), PALETTES["deep"])

    title_font = _fit_title_font(draw, title, TITLE_MAX_WIDTH)

    title_width = get_text_width(draw, title, title_font)

    # Clamp so the title can never be positioned past the safe
    # margins, even in a rounding edge case.
    title_x = max(
        TITLE_SAFE_MARGIN,
        min((VIDEO_WIDTH - title_width) // 2, VIDEO_WIDTH - TITLE_SAFE_MARGIN - title_width),
    )

    draw.text((title_x, 32), title, font=title_font, fill=palette["heading"])


def _draw_one_bullet(draw, theme, text_x, current_y, bullet_text, bullet_lines, body_font, line_height):

    bullet_color = pick_bullet_color(theme, bullet_text)

    bullet_x = text_x
    bullet_y = current_y + 6

    draw_marker(draw, bullet_x, bullet_y, 14, bullet_color, theme.get("marker", "circle"))

    text_start_x = text_x + 35

    for line_index, line in enumerate(bullet_lines):
        line_y = current_y + (line_index * line_height)
        draw.text((text_start_x, line_y), line, font=body_font, fill=bullet_color)


def _draw_bullet_block_clipped(draw, theme, text_x, current_y, bullet_text, body_font, max_width, line_height, bullet_gap):

    """
    Wraps `bullet_text`, then draws only as many of its wrapped
    lines as fully fit above BOARD_TEXT_BOTTOM_Y. This is the
    hard vertical clipping boundary: no line is ever drawn if its
    bottom edge would fall on or past BOARD_TEXT_BOTTOM_Y, so text
    can never bleed out of the board's writable area regardless of
    upstream measurement rounding. Returns the new current_y.
    """

    bullet_lines = wrap_text(draw, bullet_text, body_font, max_width - 55)

    if not bullet_lines:
        return current_y

    drawable_lines = []

    for line in bullet_lines:

        line_bottom = current_y + (len(drawable_lines) + 1) * line_height

        if line_bottom > BOARD_TEXT_BOTTOM_Y:
            break

        drawable_lines.append(line)

    if not drawable_lines:
        return current_y

    _draw_one_bullet(draw, theme, text_x, current_y, bullet_text, drawable_lines, body_font, line_height)

    return current_y + len(drawable_lines) * line_height + bullet_gap


def _draw_bullet_text(draw, scene, theme, time_position, layout):

    text_x = BOARD_TEXT_LEFT_X

    body_font = layout["body_font"]
    line_height = layout["line_height"]
    bullet_gap = layout["bullet_gap"]
    max_width = layout["max_width"]

    current_y = BOARD_TEXT_TOP_Y

    # ------------------------------------------------------
    # 1) Redraw everything already written on this board by
    #    earlier scenes - fully, statically. This is what keeps
    #    the board from ever appearing to "erase" unfinished
    #    notes just because a scene boundary passed.
    # ------------------------------------------------------

    prior_bullets = scene.get("board_prior_bullets", []) if isinstance(scene, dict) else []

    for bullet_text in prior_bullets:

        if current_y >= BOARD_TEXT_BOTTOM_Y:
            break

        current_y = _draw_bullet_block_clipped(
            draw, theme, text_x, current_y, bullet_text, body_font, max_width, line_height, bullet_gap
        )

    # ------------------------------------------------------
    # 2) Progressively reveal THIS scene's own new bullets, word
    #    by word, in sync with its narration - continuing to
    #    write below whatever step 1 already drew. Each bullet
    #    still passes through the same hard vertical clip.
    # ------------------------------------------------------

    bullet_points = layout["bullet_points"]
    word_timelines = layout["word_timelines"]

    for bullet_index, bullet_text in enumerate(bullet_points):

        if current_y >= BOARD_TEXT_BOTTOM_Y:
            break

        timeline = word_timelines[bullet_index]

        words = timeline["words"]
        word_starts = timeline["word_starts"]

        if not words:
            continue

        if not word_starts or word_starts[0] is None or time_position < word_starts[0]:
            continue

        visible_word_count = get_visible_word_count(word_starts, time_position)

        if visible_word_count <= 0:
            continue

        visible_text = " ".join(words[:visible_word_count])

        if not visible_text:
            continue

        current_y = _draw_bullet_block_clipped(
            draw, theme, text_x, current_y, visible_text, body_font, max_width, line_height, bullet_gap
        )


def _draw_footer(draw, scene):

    footer_font = load_font(18, bold=False)

    draw.text((45, 680), "Birhan AI", font=footer_font, fill=GRAY)

    scene_number = scene.get("scene_number", "")

    if scene_number:

        text = "Scene " + str(scene_number)

        width = get_text_width(draw, text, footer_font)

        draw.text((VIDEO_WIDTH - width - 45, 680), text, font=footer_font, fill=GRAY)


def _draw_progress_bar(draw, progress):

    progress = max(0.0, min(float(progress), 1.0))

    bar_x1, bar_x2 = 45, VIDEO_WIDTH - 45
    bar_y1, bar_y2 = 705, 712

    draw.rectangle([bar_x1, bar_y1, bar_x2, bar_y2], fill=(225, 225, 225))

    progress_width = int((bar_x2 - bar_x1) * progress)

    if progress_width > 0:
        draw.rectangle([bar_x1, bar_y1, bar_x1 + progress_width, bar_y2], fill=(45, 100, 180))


def create_scene_frame_at_time(scene, time_position, duration, layout=None):

    """
    Builds one complete video frame (or, when time_position >=
    duration, the "final" fully-written board used for the static
    gallery PNG) for a scene. Returns a PIL Image sized exactly
    VIDEO_WIDTH x VIDEO_HEIGHT. All text (title + bullets) is
    drawn strictly within the board's safe boundaries - see
    _draw_board_title and _draw_bullet_block_clipped.
    """

    if duration is None or duration <= 0:
        duration = 1.0
    else:
        duration = float(duration)

    if time_position is None:
        time_position = 0.0
    else:
        time_position = float(time_position)

    time_position = max(0.0, min(time_position, duration))

    theme = theme_for_scene(scene)

    camera = camera_for_scene(scene)

    transition_from_key = scene.get("camera_transition_from") if isinstance(scene, dict) else None

    transition_from_camera = CAMERA_BY_KEY.get(transition_from_key) if transition_from_key else None

    # --- content region: board background, title, bullets only ---

    content_image = Image.new("RGB", (VIDEO_WIDTH, CONTENT_HEIGHT))

    content_draw = ImageDraw.Draw(content_image)

    content_draw.rectangle(
        [0, 0, VIDEO_WIDTH - 1, CONTENT_HEIGHT - 1], fill=theme["background"]
    )

    content_draw.rectangle(
        [0, 0, VIDEO_WIDTH - 1, CONTENT_HEIGHT - 1], outline=theme["border"], width=3
    )

    content_draw.line([70, 100, VIDEO_WIDTH - 70, 100], fill=theme["divider"], width=3)

    _draw_board_title(content_draw, scene, theme)

    if layout is None:
        layout = build_scene_render_layout(draw=content_draw, scene=scene, duration=duration)

    if layout:
        _draw_bullet_text(content_draw, scene, theme, time_position, layout)

    content_image = apply_camera_transform(
        content_image,
        camera,
        transition_from=transition_from_camera,
        time_position=time_position,
        duration=duration,
    )

    # --- final frame: transformed content + fixed overlays ---

    final_image = Image.new("RGB", (VIDEO_WIDTH, VIDEO_HEIGHT))

    ImageDraw.Draw(final_image).rectangle(
        [0, 0, VIDEO_WIDTH - 1, VIDEO_HEIGHT - 1], fill=WHITE
    )

    final_image.paste(content_image, (0, 0))

    final_draw = ImageDraw.Draw(final_image)

    progress = time_position / duration

    _draw_footer(final_draw, scene)

    _draw_progress_bar(final_draw, progress)

    return final_image